### ISSUE TITLE
be_ept_tfce_diff

### ISSUE THREAD

**Issue by paulsowman** [unfoldtoolbox/unfold#58]
Hi, great toolbox. Thanks for making it available. I've been working through the tutorials and it seems that the function: be_ept_tfce_diff is not part of the toolbox. Any chance I could get a copy?

Thanks, Paul

**Comment by behinger** [comment]
Hi!
Thanks!

I never came around to make this function pretty, but I really should do it ;)
In the meanwhile here is the (non-pretty) function.
https://gist.github.com/behinger/c507559fabe0cb472d88910fdc9bf8f3

If you prefer to use robust statistics (yuens-t-test) based on winsorized mean & variance you can find it here:
https://gist.github.com/behinger/e6d60125bc7b72dc5fbf26d8073be057

The second functions needs the dependency ```limo_yuen_ttest```  which can be found here:
https://github.com/LIMO-EEG-Toolbox/limo_eeg/blob/master/limo_yuend_ttest.m

My plan is to combine these functions so that one can easily exchange the statistics in a functional programming way. But I didn't came around to do it yet.


Please note that you are completly free to use whatever statistics you want to do, our main goal is to write a 1st level deconvolution toolbox and let the user choose their 2nd (group) level statistical analysis.

**Comment by paulsowman** [comment]
Thanks, much appreciated. I’m looking for that instant gratification of getting to the end of the tutorial with an output that looks pretty like yours! 

 

Thanks again for the tools. P
